USE onpoint;

DROP TABLE IF EXISTS mark;
DROP TABLE IF EXISTS mark_type;

CREATE TABLE `mark_type` (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL UNIQUE,
  PRIMARY KEY (id)
) ENGINE=INNODB;

CREATE TABLE `mark` (
  id INT AUTO_INCREMENT,
  when_happened TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  marked_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  marked_type_id INT,
  PRIMARY KEY (id),
  FOREIGN KEY (marked_type_id) REFERENCES mark_type(id)
) ENGINE=INNODB;